---
title: 'Archive'
output:
    html_document:
        template: './_templates/default.html'
---

### 2020

- 3 July 2020 [Reclassification of gabapentinoids as schedule 3 controlled substances in England: an interrupted time series analysis](https://www.painblogr.org/2020-07-03-piecewise-regression.html) 

- 19 June 2020 [Neat and tidy data exploration with list-columns and _purrr_](https://www.painblogr.org/2020-06-19-purring-through-exploratory-analyses.html) 

- 14 June 2020 [So you think investing in fever screening can curb the spread of COVID-19? Think again](https://www.painblogr.org/2020-06-14-covid-fevers.html)

- 15 March 2020 [COVID-19 in South Africa](https://covid19za.netlify.app/)

### 2019

- 9 March 2019 [Arthritis in the USA](https://www.painblogr.org/2019-03-09-pain-in-the-usa.html)

- 25 January 2019 [When your ‘golden years’ are not so golden](https://www.painblogr.org/2019-01-25-global-burden-of-disease.html)


### 2017
- 18 October 2017 ['purrr'-ing through bootstrap confidence intervals](https://www.painblogr.org/2017-10-18-purrring-through-bootstraps.html)  

- 5 February 2017 [How quickly do the top four pain-specific journals convert from _epub ahead of print_ to _print copy_?](https://www.painblogr.org/2017-02-05-publication-time.html)

- 11 February 2017 [Too few medicines to treat neuropathic pain on national essential medicines lists](https://www.painblogr.org/2017-02-11-eml-drug-map.html)


### 2016

- 19 September 2016 [Neuropathic pain: So many people, but where are the drugs?](https://www.painblogr.org/2016-09-19-neuropathic-pain-storyboard.html)

- 17 May 2016 [The gganimate package in action: Probability theory](https://www.painblogr.org/2016-05-17-probability-theory.html) (updated  27 January 2019)

- 18 Mar 2016 [Quick comment: Article Processing Charges (APC)](https://www.painblogr.org/2016-03-18-article-processing-charges.html)

- 22 Feb 2016 [HIV neuropathy: down, but not out](https://www.painblogr.org/2016-02-22-hiv-neuropathy-down-but-not-out.html)

### 2015

- 26 Nov 2015 [Access to raw data from preclinical studies](https://www.painblogr.org/2015-11-26-access-to-raw-data.html)

- 25 Nov 2015 [Hot off the press: South African cancer pain guidelines](https://www.painblogr.org/2015-11-25-south-african-cancer-pain-guidelines.html)

- 19 Nov 2015 [Explainer: what is pain and what is happening when we feel it?](https://www.painblogr.org/2015-11-19-explainer-what-is-pain.html)
